# Generated by Django 5.1.5 on 2025-02-01 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacyprofile',
            name='ownerID',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='lname',
        ),
        migrations.AddField(
            model_name='owner',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='owner',
            name='nationalID',
            field=models.CharField(max_length=14),
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('license_number', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacies', to='accounts.owner')),
            ],
        ),
    ]
