# Generated by Django 5.1.5 on 2025-02-01 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_pharmacyprofile_ownerid_and_more'),
        ('medicine', '0002_alter_medicine_exp_date_alter_medicine_pharmacy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PharmacyProfile',
        ),
    ]
