POST https://127.0.0.1:8000/exchange/buy/order HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwODY1ODk3LCJpYXQiOjE3NTA4NjQ5OTcsImp0aSI6IjU2NWI4YzNjMmI3NDQ5YTdiYmUxN2RlODlhZTE4NjE3IiwidXNlcl9pZCI6MjAsInBoYXJtYWN5X2lkIjoiNDAifQ.P15oRf5vOTabyml7chhOHkaSqgln852Dk9hpnQg-5nE


{

    "medicine_name": "kohol",
    "quantity": 3,
    "pharmacy_seller": "العطا",
    "pharmacy_buyer": "elhamdy",
    "price": 50.0
}

###

GET https://127.0.0.1:8000/exchange/get/pharmcy_seller/orders HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwODY1OTUxLCJpYXQiOjE3NTA4NjUwNTEsImp0aSI6IjMxMjNkMWIxYjkzZjQ1ODBiZmFmN2U0NmJiNTQxZjMxIiwidXNlcl9pZCI6MywicGhhcm1hY3lfaWQiOiIyIn0.gvR2HEIj7GUOOPy3w4B9rPruxXX5rw5TSlWGtwN_kBc


###

# GET https://smart-pharma-net.vercel.app/exchange/get/pharmcy_seller/orders HTTP/1.1
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwNTEwMDk1LCJpYXQiOjE3NTA1MDkxOTUsImp0aSI6IjZkYmZjOWViMDZhZjQyYzZiZjRlODY2MjVmNGFlYmU0IiwidXNlcl9pZCI6MywicGhhcm1hY3lfaWQiOiIyIn0.0DGXD0gtl1BBk_Bm6dWZ3LJxIRGgLFQNzttLJTmG47o

###

PATCH https://127.0.0.1:8000/exchange/update_status/147 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwODY1OTUxLCJpYXQiOjE3NTA4NjUwNTEsImp0aSI6IjMxMjNkMWIxYjkzZjQ1ODBiZmFmN2U0NmJiNTQxZjMxIiwidXNlcl9pZCI6MywicGhhcm1hY3lfaWQiOiIyIn0.gvR2HEIj7GUOOPy3w4B9rPruxXX5rw5TSlWGtwN_kBc

{
    "status": "Completed"
}

###

POST  https://127.0.0.1:8000/account/pharmacy/login/ HTTP/1.1
Content-Type: application/json

{

   "name": "elhamdy",
    "password": "123"
}



###


POST  https://127.0.0.1:8000/account/pharmacy/login/ HTTP/1.1
Content-Type: application/json

{

   "name": "العطا",
    "password": "123"
}


###


GET https://127.0.0.1:8000/exchange/get_notification HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwODY2MDI0LCJpYXQiOjE3NTA4NjUxMjQsImp0aSI6IjM2ZDgxMzM1NTVkYzRhOTdiOTg5YjZlNmIyZTQ1YTVkIiwidXNlcl9pZCI6MjAsInBoYXJtYWN5X2lkIjoiNDAifQ.QJaC7gcz75qx4JKINWD2KAoCSe0vOPMaTK9ubYf8aNI
