POST https://127.0.0.1:8000/exchange/buy/order HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwOTc2MDE2LCJpYXQiOjE3NTA5NzUxMTYsImp0aSI6IjU2YmUwYzEyODhhOTQwN2FiYzg2MTBmMzNkMzFhMWI4IiwidXNlcl9pZCI6MjAsInBoYXJtYWN5X2lkIjoiNDAifQ.YcmfW45CEvJF4u04P6Y19kjXVuRD6IJW_svZL7a4KnQ

{

    "medicine_name": "panadol extra",
    "quantity": 10,
    "pharmacy_seller": "ameer",
    "pharmacy_buyer": "elhamdy",
    "price": 100
}


###

POST  https://127.0.0.1:8000/exchange/user_purchase/ HTTP/1.1
Content-Type: application/json

{
    "username": "elh",
    "email": "youss@gmail.com",
    "phone_number": "01012345678",
    "address": "123 Main St, Cairo",
    "medicine": "kohol"
}


###

GET https://127.0.0.1:8000/exchange/get/pharmcy_seller/orders HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwOTc2MDUwLCJpYXQiOjE3NTA5NzUxNTAsImp0aSI6ImNmNjYwNTYzYjgxOTRkNGE5MmUwOWE1YzM2MjdhNjZjIiwidXNlcl9pZCI6NCwicGhhcm1hY3lfaWQiOiIyMiJ9.E0HkraOH31zg9fS0RSBS3lbkmGUld51dpwUL4LvS-Mw


###

# GET https://smart-pharma-net.vercel.app/exchange/get/pharmcy_seller/orders HTTP/1.1
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwNTEwMDk1LCJpYXQiOjE3NTA1MDkxOTUsImp0aSI6IjZkYmZjOWViMDZhZjQyYzZiZjRlODY2MjVmNGFlYmU0IiwidXNlcl9pZCI6MywicGhhcm1hY3lfaWQiOiIyIn0.0DGXD0gtl1BBk_Bm6dWZ3LJxIRGgLFQNzttLJTmG47o

###

PATCH https://127.0.0.1:8000/exchange/update_status/170 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwOTc2MDUwLCJpYXQiOjE3NTA5NzUxNTAsImp0aSI6ImNmNjYwNTYzYjgxOTRkNGE5MmUwOWE1YzM2MjdhNjZjIiwidXNlcl9pZCI6NCwicGhhcm1hY3lfaWQiOiIyMiJ9.E0HkraOH31zg9fS0RSBS3lbkmGUld51dpwUL4LvS-Mw

{
    "status": "Completed"
}

###

POST  https://127.0.0.1:8000/account/pharmacy/login/ HTTP/1.1
Content-Type: application/json

{

   "name": "elhamdy",
    "password": "123"
}



###


POST  https://127.0.0.1:8000/account/pharmacy/login/ HTTP/1.1
Content-Type: application/json

{

   "name": "ameer",
    "password": "123456"
}


###


GET https://127.0.0.1:8000/exchange/get_notification HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwODY2MDI0LCJpYXQiOjE3NTA4NjUxMjQsImp0aSI6IjM2ZDgxMzM1NTVkYzRhOTdiOTg5YjZlNmIyZTQ1YTVkIiwidXNlcl9pZCI6MjAsInBoYXJtYWN5X2lkIjoiNDAifQ.QJaC7gcz75qx4JKINWD2KAoCSe0vOPMaTK9ubYf8aNI


