POST https://127.0.0.1:8000/exchange/buy/order/ HTTP/1.1
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyNTg1ODAzLCJpYXQiOjE3NTI1ODQ5MDMsImp0aSI6IjdmZWVkNDg0ODkyOTQzNDc5NTM5NTVlYjJlMWQwMzI2IiwidXNlcl9pZCI6NiwicGhhcm1hY3lfaWQiOiI4In0.yqjCJvg4sUdmCBJcYJZu0MQkhYQ4e5YsYy-8K56lqt0


{
    "medicine_name": "test the orders",
    "price": 50.0,
    "pharmacy_seller": "Dr. joo",
    "pharmacy_buyer": "Dr. youssef",
    "recieve_date": "2026-01-01T10:00:00Z",
    "quantity": 25
}


# gamal
# "medicine_name": "clavimox",
#     "medicine_price_to_sell": "12990.00",
#     "medicine_quantity_to_sell": "1200",
#     "pharmacy_name": "gamal",
#     "pharmacy_latitude": "31.244706",
#     "pharmacy_longitude": "32.324224",
#     "medicine_image": "https://cdn.supercommerce.io/sally/uploads/145751.webp"


  # elhamdy
  #  "medicine_name": "test",
  #   "medicine_price_to_sell": "1200.00",
  #   "medicine_quantity_to_sell": "999",
  #   "pharmacy_name": "elhamdy",
  #   "pharmacy_latitude": "31.259262",
  #   "pharmacy_longitude": "32.284702",
  #   "medicine_image": "http://admissions.rochester.edu/blog/wp-content/uploads/2015/08/test.png"
###


PUT  https://127.0.0.1:8000/exchange/update_status/70/ HTTP/1.1
Content-Type: application/json
Authorization:  Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyNTg4Mzg0LCJpYXQiOjE3NTI1ODc0ODQsImp0aSI6IjMwNjFmZGY0OTQ3ZDQyNDA4ZmExZGMyYWQ2MDBiOWU1IiwidXNlcl9pZCI6NiwicGhhcm1hY3lfaWQiOiI3In0.eTL3nly6197Pe7Gnl4M4XoYGT9hPvTZ5jKZQ5Ez1DEg


{

    "status": "Completed"
  
}


###


GET  https://127.0.0.1:8000/exchange/exchange_list/ HTTP/1.1
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyMDExNzY2LCJpYXQiOjE3NTIwMTA4NjYsImp0aSI6ImFjODY3YmEzM2IwOTQxNzU4NjQwZDNmZTZlMjgwM2RkIiwidXNlcl9pZCI6MjB9.Gkxr0i6kByDHEOLwxl6GcANDjXsOyfelSc-m3xupid8






###



GET https://127.0.0.1:8000/exchange/get/pharmcy_seller/orders/ HTTP/1.1
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyNTg4Mzg0LCJpYXQiOjE3NTI1ODc0ODQsImp0aSI6IjMwNjFmZGY0OTQ3ZDQyNDA4ZmExZGMyYWQ2MDBiOWU1IiwidXNlcl9pZCI6NiwicGhhcm1hY3lfaWQiOiI3In0.eTL3nly6197Pe7Gnl4M4XoYGT9hPvTZ5jKZQ5Ez1DEg


###

GET https://127.0.0.1:8000/account/dashboard/ HTTP/1.1
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxODMzODUwLCJpYXQiOjE3NTE4MzI5NTAsImp0aSI6IjhkMWU4OTkzMjYyNjQ4ZWZhN2ZmNGNiZmYyZWY1ZGNhIiwidXNlcl9pZCI6MjB9.rZbtMosFq3NlcOAFca9QSaeNHMcdTmSvtFuYe3l-00Y




###

GET  https://127.0.0.1:8000/exchange/get_notification/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyMDc5OTMxLCJpYXQiOjE3NTIwNzkwMzEsImp0aSI6IjVlMjkxZGQ1NWE4ZDQxZGZiMjQ1ZGNlZjMxNGFhNmM2IiwidXNlcl9pZCI6MjAsInBoYXJtYWN5X2lkIjoiNDAifQ.3P79kF4qcZXGjWVlC8fjouh9lbDtvKdmoXRz5XWVupw




###

POST https://127.0.0.1:8000/account/pharmacy/login/ HTTP/1.1
Content-Type: application/json

{
  "name": "gamal",
  "password": "123"

}


###

POST   https://127.0.0.1:8000/account/pharmacy/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyMjE0NjE0LCJpYXQiOjE3NTIyMTM3MTQsImp0aSI6IjlmN2Y2ODIzZWM4ODRmNTRhYzZlMjRkMmZhZGZlMDQ4IiwidXNlcl9pZCI6Nn0.c79sh9onRfNnSwe9Obfa4ptEr_6L5iMdKmskuGH6nS4

{

  "name": "Dr. youssef",
  "city": "port said",
  "latitude": "31.259262",
  "longitude": "32.284702",
  "license_number": "123456789",
  "number_sells": 0,
  "number_buys": 0,
  "password": "123",
  "confirm_password": "123"
}

###

GET https://127.0.0.1:8000/exchange/exchange_list/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyNTg1NTUxLCJpYXQiOjE3NTI1ODQ2NTEsImp0aSI6IjAyZjg3NjllZGUzNzQ0NGE5ZDQ0MmQ5NmZiNDE4YTZmIiwidXNlcl9pZCI6Nn0.--tdTzyPVeKTT43lPK5WDZ9dIgDaUP5Mv7Sq3U1lC2U


###


POST https://127.0.0.1:8000/account/pharmacy/login/ HTTP/1.1
Content-Type: application/json

{
  "name": "Dr. youssef",
  "password": "123"
}

###


GET https://127.0.0.1:8000/exchange/get_orders_request/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyNTg4NTA5LCJpYXQiOjE3NTI1ODc2MDksImp0aSI6IjUyZDJiM2E0NzFmNzQwNjM4MzliZmFlYTM0OTRmZTUzIiwidXNlcl9pZCI6NiwicGhhcm1hY3lfaWQiOiI4In0.5m78ZG5uO53cItdlwjKUfF9Ofo2hBhRMbJoT_PwCEmY



###


GET  https://127.0.0.1:8000/medicine/medicines/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyNTg1NjU5LCJpYXQiOjE3NTI1ODQ3NTksImp0aSI6ImFkMTVjMTA5ZDkyYTQ3NjZiMTc4MDkyNjY2Y2ViOWJkIiwidXNlcl9pZCI6NiwicGhhcm1hY3lfaWQiOiI4In0.Dr94-03m-eTiIZogISTwtLJrPiitsG5hFh-XIysFOec



###
POST https://127.0.0.1:8000/account/pharmacy/login/ HTTP/1.1
Content-Type: application/json

{
  "name": "Dr. joo",
  "password": "123"

}
###


GET   https://127.0.0.1:8000/medicine/medicines/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyNTg1NzQ1LCJpYXQiOjE3NTI1ODQ4NDUsImp0aSI6ImFlNzA3MGMzODZlYjQyOTQ5MjZlMzgxMTZjMGJiNzQyIiwidXNlcl9pZCI6NiwicGhhcm1hY3lfaWQiOiI3In0.bXNTfasvR0T6i_sTcSZTVjaSd06-9zJ519vC-t8JdyE


{
  "name": "test the orders",
  "category": "Antibiotics",
  "price": 50.0,
  "quantity": 100,
  "quantity_to_sell":50,
  "can_be_sell": true,
  "description":"This is a test medicine for caching purposes.",
  "exp_date": "2025-12-31"
}


###


POST https://smart-pharma-net.vercel.app/account/register/ HTTP/1.1
Content-Type: application/json


  {
    "user": {
      "first_name": "youssef",
      "last_name": "Hesham",
      "username": "joo_elh",
      "email": "youssef4923@gmail.com",
      "password": "492003492003"
    },
    "gender": "M",
    "phone": "01276785722",
    "nationalID": "30309040300398"
  }





###
POST https://127.0.0.1:8000/account/owner/login/ HTTP/1.1
Content-Type: application/json

{
  "email": "youss4923@gmail.com",
  "password": "12345678"

}






