# Generated by Django 5.1.5 on 2025-04-21 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '0003_alter_medicine_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeMedciene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('Sell', 'Sell'), ('Buy', 'Buy')], max_length=5)),
                ('quantity', models.IntegerField(default=1)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='medicine.medicine')),
            ],
        ),
    ]
