# Generated by Django 5.1.5 on 2025-04-23 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
        ('medicine', '0010_medicine_can_be_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangemedciene',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_entries', to='medicine.medicine'),
        ),
    ]
