# Generated by Django 5.1.5 on 2025-05-07 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_pharmacy_location_pharmacy_city_and_more'),
        ('exchange', '0002_alter_exchangemedciene_medicine'),
        ('medicine', '0013_medicine_buy_medicine_quantity_to_buy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine')),
                ('pharmacy_buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.pharmacy')),
            ],
        ),
    ]
