# Generated by Django 5.1.5 on 2025-05-07 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_order_exchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_exchange',
            name='pharmacy_buyer',
        ),
    ]
