# Generated by Django 5.1.5 on 2025-06-14 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_remove_order_exchange_pharmacy_buyer'),
        ('medicine', '0016_remove_medicine_buy_remove_medicine_quantity_to_buy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_exchange',
            new_name='Buy_Order',
        ),
    ]
