# Generated by Django 5.1.5 on 2025-06-14 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_pharmacy_location_pharmacy_city_and_more'),
        ('exchange', '0005_rename_order_exchange_buy_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy_order',
            name='medicine',
        ),
        migrations.AddField(
            model_name='buy_order',
            name='medicine_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buy_order',
            name='pharmacy_buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.pharmacy'),
        ),
        migrations.AddField(
            model_name='buy_order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
