# Generated by Django 5.1.5 on 2025-06-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_remove_buy_order_medicine_buy_order_medicine_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy_order',
            old_name='pharmacy_buyer',
            new_name='pharmacy_seller',
        ),
        migrations.AlterField(
            model_name='buy_order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
