# Generated by Django 5.1.5 on 2025-06-16 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0011_alter_buy_order_pharmacy_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy_order',
            name='pharmacy_seller',
        ),
    ]
