# Generated by Django 5.1.5 on 2025-06-16 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_pharmacy_location_pharmacy_city_and_more'),
        ('exchange', '0012_remove_buy_order_pharmacy_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_order',
            name='pharmacy_seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.pharmacy'),
        ),
    ]
