# Generated by Django 5.1.5 on 2025-06-16 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_pharmacy_location_pharmacy_city_and_more'),
        ('exchange', '0019_alter_buy_order_pharmacy_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_order',
            name='pharmacy_seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.pharmacy'),
        ),
    ]
