# Generated by Django 5.1.5 on 2025-06-16 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_pharmacy_location_pharmacy_city_and_more'),
        ('exchange', '0022_alter_buy_order_pharmacy_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_order',
            name='pharmacy_buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_orders', to='accounts.pharmacy'),
        ),
        migrations.AlterField(
            model_name='buy_order',
            name='pharmacy_seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_orders', to='accounts.pharmacy'),
        ),
    ]
