# Generated by Django 5.1.5 on 2025-06-18 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_pharmacy_location_pharmacy_city_and_more'),
        ('exchange', '0024_remove_buy_order_pharmacy_buyer_and_more'),
        ('medicine', '0016_remove_medicine_buy_remove_medicine_quantity_to_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_order',
            name='pharmacy_buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_bought', to='accounts.pharmacy'),
        ),
        migrations.AlterField(
            model_name='buy_order',
            name='medicine_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine'),
        ),
        migrations.AlterField(
            model_name='buy_order',
            name='pharmacy_seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_sold', to='accounts.pharmacy'),
        ),
        migrations.AlterField(
            model_name='buy_order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='buy_order',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='buy_order',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
