# Generated by Django 5.1.5 on 2025-06-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0025_buy_order_pharmacy_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
    ]
