# Generated by Django 5.1.5 on 2025-06-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0026_alter_buy_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_order',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
    ]
