# Generated by Django 5.1.5 on 2025-06-23 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_pharmacy_location_pharmacy_city_and_more'),
        ('exchange', '0033_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribtion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Free', 'Free'), ('Pro', 'Pro'), ('Max', 'Max')], default='Free', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.pharmacy')),
            ],
        ),
    ]
