# Generated by Django 5.1.5 on 2025-07-10 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0033_notification_subscription'),
        ('exchange', '0036_userpurchase'),
    ]

    operations = [
    ]
