# Generated by Django 5.1.5 on 2025-06-28 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0036_userpurchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpurchase',
            name='created_at',
        ),
    ]
