# Generated by Django 5.1.5 on 2025-06-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0039_alter_userpurchase_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpurchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
