# Generated by Django 5.1.5 on 2025-07-06 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0033_notification_subscription'),
        ('exchange', '0041_alter_userpurchase_created_at'),
    ]

    operations = [
    ]
