# Generated by Django 5.1.5 on 2025-07-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0042_merge_20250706_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpurchase',
            name='typer_purchase',
            field=models.CharField(choices=[('visa', 'Visa'), ('cash_on_delivery', 'Cash On Delivery')], default='cash_on_delivery', max_length=50, null=True),
        ),
    ]
