# Generated by Django 5.1.5 on 2025-07-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0043_userpurchase_typer_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpurchase',
            old_name='typer_purchase',
            new_name='type_purchase',
        ),
    ]
