# Generated by Django 5.1.5 on 2025-07-08 17:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0044_rename_typer_purchase_userpurchase_type_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_order',
            name='recieve_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
