# Generated by Django 5.1.5 on 2025-07-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0045_buy_order_recieve_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_order',
            name='recieve_date',
            field=models.DateTimeField(default=None),
        ),
    ]
