# Generated by Django 5.1.6 on 2025-03-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
