# Generated by Django 5.1.5 on 2025-04-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pharmacy_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='location',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
