# Generated by Django 5.1.5 on 2025-07-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_pharmacy_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='created_at',
        ),
        migrations.AddField(
            model_name='owner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
