# Generated by Django 5.1.5 on 2025-07-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_pharmacy_created_at_owner_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='number_buys',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='number_sells',
            field=models.IntegerField(default=0),
        ),
    ]
