# Generated by Django 5.1.6 on 2025-03-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_medicine_price_alter_medicine_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('Dental and oral agents', 'Dental and oral agents'), ('Blood products', 'Blood products'), ('Antibiotics', 'Antibiotics')], max_length=50),
        ),
    ]
