# Generated by Django 5.1.5 on 2025-04-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_alter_medicine_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='can_be_sell',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicine',
            name='medicine_quantity_to_sell',
            field=models.PositiveIntegerField(default=-1023),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='price_to_sell',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
