# Generated by Django 5.1.5 on 2025-04-22 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_medicine_can_be_sell_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='medicine_quantity_to_sell',
            new_name='quantity_to_sell',
        ),
    ]
