# Generated by Django 5.1.5 on 2025-04-22 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_rename_medicine_quantity_to_sell_medicine_quantity_to_sell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='can_be_sell',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='price_to_sell',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='quantity_to_sell',
        ),
    ]
