# Generated by Django 5.1.5 on 2025-04-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_remove_medicine_can_be_sell_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='quantity_to_sell',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
