# Generated by Django 5.1.5 on 2025-04-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0007_medicine_quantity_to_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='quantity_to_sell',
            field=models.IntegerField(null=True),
        ),
    ]
