# Generated by Django 5.1.5 on 2025-04-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0008_alter_medicine_quantity_to_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='price_sell',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
