# Generated by Django 5.1.5 on 2025-04-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0009_medicine_price_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='can_be_sell',
            field=models.BooleanField(default=False),
        ),
    ]
