# Generated by Django 5.1.5 on 2025-04-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0010_medicine_can_be_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='can_be_sell',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
