# Generated by Django 5.1.5 on 2025-04-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0011_alter_medicine_can_be_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='quantity_to_sell',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
