# Generated by Django 5.1.5 on 2025-05-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0012_alter_medicine_quantity_to_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='Buy',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='quantity_to_Buy',
            field=models.IntegerField(null=True),
        ),
    ]
