# Generated by Django 5.1.5 on 2025-06-13 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0013_medicine_buy_medicine_quantity_to_buy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='Buy',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='quantity_to_Buy',
        ),
    ]
