# Generated by Django 5.1.5 on 2025-06-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0014_remove_medicine_buy_remove_medicine_quantity_to_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='Buy',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='quantity_to_Buy',
            field=models.IntegerField(null=True),
        ),
    ]
