# Generated by Django 5.1.5 on 2025-06-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0016_remove_medicine_buy_remove_medicine_quantity_to_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
