# Generated by Django 5.1.5 on 2025-06-28 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0016_remove_medicine_buy_remove_medicine_quantity_to_buy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='category',
        ),
    ]
