# Generated by Django 5.1.5 on 2025-06-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0018_medicine_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('Dental and oral agents', 'Dental and oral agents'), ('Blood products', 'Blood products'), ('Antibiotics', 'Antibiotics')], max_length=50),
        ),
    ]
