# Generated by Django 5.1.5 on 2025-07-06 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0017_medicine_image_url'),
        ('medicine', '0019_alter_medicine_category'),
    ]

    operations = [
    ]
